defaults:
  -
     scope:
       path: ""
     values:
       layout: "default"
       supported_drivers: "[DB] is &quot;MySQL.MySQL_Driver&quot;, &quot;PgSQL.PgSQL_Driver&quot;, or &quot;SQLite.SQLite_Driver&quot;"
       trait_client: '<a href="trait_client.html">client traits</a>'
       trait_server: '<a href="trait_server.html">server traits</a>'
       trait_driver: '<a href="trait_driver.html">driver identification</a>'
       trait_autocommit: '<a href="autocommit.html">autocommit settings</a>'
       trait_column_case: '<a href="column_case.html">column case settings</a>'
       trait_error_mode: '<a href="error_mode.html">error mode settings</a>'
       trait_blob_size: '<a href="max_blob_size.html">BLOB size settings</a>'
       trait_compressed: '<a href="trait_compressed.html">compression settings [DS]</a>'
       trait_multiquery: '<a href="trait_multiquery.html">multiquery settings [DS]</a>'
       trait_buffers: '<a href="trait_buffers.html">query buffer settings [DS]</a>'
       screen_logger: '<a href="screen_logger.html">logging to screen</a>'
       query: '<a href="query.html">query</a>'
       execute: '<a href="execute.html">execute (driver)</a>'
       rollback: '<a href="rollback.html">rollback</a>'
       commit: '<a href="commit.html">commit</a>'
       connect: '<a href="connect.html">connect</a>'
       disconnect: '<a href="disconnect.html">disconnect</a>'
       driver_msg: '<a href="last_driver_message.html">last driver message</a>'
       driver_code: '<a href="last_driver_code.html">last driver code</a>'
       driver_state: '<a href="last_driver_state.html">last driver state</a>'
